version: "3.3"

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: shive
      POSTGRES_USER: shive
      POSTGRES_PASSWORD: shive
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U shive" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://shive:shive@database:5432/shive
    ports:
      - "80:8000"
    depends_on:
      - database
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
