version: "3.3"

services:
  test-database:
    image: postgres:latest
    environment:
      POSTGRES_DB: test_shive
      POSTGRES_USER: shive
      POSTGRES_PASSWORD: shive
    expose: 
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433